films/urls.py
from django.urls import path
from . import views

app_name = 'films'
urlpatterns = [
    path('', views.main, name='main'),
    path('user_info/', views.user_info, name='user_info'),
    path('user_form/', views.user_form, name= 'user_form'),
    path('<int:id>/details', views.details, name='details'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from films import views    # added 

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('films/', include('films.urls')),
    path('gapminder/<int:year>', views.gapminder, name='gapminder'),
]

films/models.py
from django.db import models


class Genre(models.Model):
    name = models.CharField(max_length=150)
    
    def __str__(self):
        return self.name


class Film(models.Model):
    title = models.CharField(max_length=200)
    year = models.PositiveIntegerField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    # the Film model has a foreign key column called genre, with a one-to-many relationship
    
    def __str__(self):
        return self.title

films/views.py
# from django.http import HttpResponse


from django.shortcuts import render, redirect
from django.urls import reverse
from .models import Film
import plotly.express as px

def get_data():
    df = px.data.gapminder()
    return df
def create_plot(df, year):
    fig = px.scatter(
      data_frame = df.query(f'year=={year}'),
      x = 'gdpPercap',
      y = 'lifeExp',
      color = 'continent',
      size = 'pop',
      height = 500,
      log_x=True,
      size_max=60,
      hover_name="country")
      
    fig =  fig.to_html()
    return fig

def home(request):
    return render(request, 'home.html')


def main(request):
    title = 'Main Page'
    films_list = Film.objects.all()
    context = {'title': title,
               'films_list': films_list}
    return render(request,
                  'films/main.html',
                  context)

def details(request, id):
    film = Film.objects.get(id=id)
    # other query option: can also be used to query for just a single element by id.
    # film = Film.objects.filter(id=id)[0]
    context = {'film': film}
    return render(request, 'films/details.html', context)

def user_info(request):
    if request.method == 'GET':    
        print('\n\nrequest.GET ==>>',
              request.GET,
              '\n\n')
    
        if request.session.get('username', False):
            userinfo = {
                'username': request.session['username'],
                'country': request.session['country'],
            }
        else:
            userinfo = False
            
        context = {'userinfo': userinfo,
                   'title': 'User Info Page'}
        template = 'films/user_info.html'
        return render(request,
                      template,
                      context)
  

def user_form(request):
    if request.method == 'GET':
        context = {'title': 'User Form Page'}
        template = 'films/user_form.html'

        return render(request,
                      template,
                      context)
        
    elif request.method == 'POST':
        username = request.POST.get('username')
        country = request.POST.get('country')
        request.session['username'] = username
        request.session['country'] = country

        return redirect(reverse('films:user_info'))
    
def gapminder(request, year):
    df = get_data()
    fig = create_plot(df, year)
    context = {"plot": fig, "year": year}
    template = 'gapminder.html'
    return render(request, template, context)

# def user_info(request):
#     if request.method == 'GET':
#         # remove this print later
#         print('\n\nrequest.GET ==>>',
#               request.GET,
#               '\n\n')
    
#         userinfo = {
#             'username': request.GET.get('username'),
#             'country': request.GET.get('country'),
#         }
#         context = {'userinfo': userinfo,
#                    'title': 'User Info Page'}
#         template = 'films/user_info.html'
#         return render(request,
#                       template,
#                       context)
        
#     elif request.method == 'POST':
#         return HttpResponse('POST request here.')


# def user_info(request):
#     userinfo = {
#         'username': 'Quinn', # Put your name here
#         'country': 'Birdland', # Put your country here
#     }
#     context = {'userinfo': userinfo,
#                'title': 'User Info Page'}
    
#     return render(request,
#                   'films/user_info.html',
#                   context)

# def home(request):
#     # remove these print statements later
#     print('\n\nRequest object:', request)
#     print('Request object type:', type(request), '\n\n')
    
#     html_tags = '''
#     <h1>This is the Home Page</h1>
#     <h3>Thanks for visiting us</h3>
#     <p>MVT means:</p>
#     <ul>
#       <li>Model</li>
#       <li>View</li>
#       <li>Template</li>
#     </ul>'''
    
#     response = HttpResponse(html_tags)
#     # remove these print statements later
#     print('Response object:', response)
#     print('Response object type:', type(response))
#     print('\n\nUser-agent info :', end='')
#     print(request.META['HTTP_USER_AGENT'], '\n\n')
   
#     return response

# def main(request):
#     message = '<h1>This is the films MAIN page.</h1>'
#     return HttpResponse(message)

# def user_info(request):
#     message = '<h1>This is the films USER_INFO page.</h1>'
#     return HttpResponse(message)

films/templates/films/details.html
{% extends 'base.html' %} {% block content %}
<h1>Film details:</h1>
<br />
<table class="table" style="width: 30%">
  <thead>
    <tr>
      <th scope="col">Attribute</th>
      <th scope="col">Value</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td scope="row">Title:</td>
      <td class="text-dark">{{film.title}}</td>
    </tr>
    <tr>
      <td scope="row">Year:</td>
      <td>{{film.year}}</td>
    </tr>
    <tr>
      <td>Genre:</td>
      <td>{{film.genre}}</td>
    </tr>
  </tbody>
</table>
{% endblock %}

films/templates/films/main.html
{% extends 'base.html' %} {% block content %}
<h1>This is the films MAIN page</h1>
<br />
<h4>Films saved in our database:</h4>
<ul>
  {% for film in films_list %}

  <li>{{film.title}} ({{film.year}}, genre: "{{film.genre}}")</li>
  {% endfor %}
</ul>
{% comment %}
<ul>
  {% for number in '012'|make_list %}
  <li>Toy Story {{forloop.counter}}</li>
  {% endfor %}
</ul>
{% endcomment %} {% endblock %}

films/templates/films/user_form.html
{% extends 'base.html' %} {% block content %}

<div class="container-fluid d-flex justify-content-center">
  <form method="POST" action="" sytle="width: 40%;">
    <!-- ADD THIS TAG IN HTML FORMS WITH POST REQUESTS-->
    {% csrf_token %}

    <div class="form-group">
      <label for="exampleInputEmail1">Enter Name</label>
      <input
        name="username"
        type="text"
        class="form-control my-2"
        id="exampleInputEmail1"
        aria-describedby="emailHelp"
        placeholder="Enter email"
      />
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Enter Country</label>
      <input
        name="country"
        type="text"
        class="form-control my-2"
        id="exampleInputPassword1"
        placeholder="Password"
      />
    </div>
    <button type="submit" class="btn btn-primary mt-2">Submit</button>
  </form>
</div>

{% endblock %}

films/templates/films/user_info.html
{% extends 'base.html' %} {% block content %}
<h1>This is the films USER_INFO page</h1>
<br />
{% if userinfo %}
<h4>username: {{userinfo.username}}</h4>
<h4>country: {{userinfo.country}}</h4>
{% else %}
<h4>username: not informed</h4>
<h4>country: not informed</h4>
{% endif %} {% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />

    <!-- INSERT ADITIONAL INFORMATION TO THE HEAD TAG HERE-->
    {% block head %} {% endblock%}

    <!-- CHANGES THE PAGE TITLE IF THE VARIABLE "title" IS PASSED BY THE VIEW -->
    {% if title %}
    <title>{{title}}</title>
    {% else %}
    <!-- USE DEFAULT TITLE TEXT IF NO VARIABLE "title" IS PASSED BY THE VIEW -->
    <title>My Films App</title>
    {% endif %}
  </head>
  <body>
    <!-- BOOTSTRAP NAVBAR CODE -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div
        class="d-flex justify-content-between px-5 mx-auto"
        style="width: 90%"
      >
        <span class="navbar-text text-white">FIRST DJANGO APP</span>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link active" href="{% url 'home' %}">Home</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link active" href="{% url 'films:main' %}">Films</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link active" href="{% url 'films:user_info' %}"
              >UserInfo</a
            >
          </li>
          <li class="nav-item active">
            <a class="nav-link active" href="{% url 'films:user_form' %}"
              >UserForm</a
            >
          </li>
        </ul>
      </div>
    </nav>
    <!-- END OF NAVBAR CODE-->

    <div class="container-fluid mt-5" style="max-width: 80%">
      <!-- INSERT THE CONTENT FROM SPECIFIC PAGES HERE-->
      {% block content %} {% endblock %}
    </div>

    <footer class="bg-light text-center text-lg-start">
      <!-- Copyright -->
      <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
        © 2023 Copyright:
        <a class="center-align text-dark" href="/admin">Admin Login</a>
      </div>
      <!-- Copyright -->
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

templates/gapminder.html
{% extends 'base.html' %} {% block content %}
<h1 class="text-center">GAPMINDER (YEAR {{year}})</h1>
<div class="container-fluid d-flex justify-content-center">{{plot | safe}}</div>
{% endblock %}

templates/home.html
{% extends 'base.html' %} {% block content %}
<h1>This is the Home Page</h1>
<br />
<h3>Thanks for visiting us</h3>
<br />
<p>MVT means:</p>
<ul>
  <li>Model</li>
  <li>View</li>
  <li>Template</li>
</ul>
<h3>Link to the website pages:</h3>
<ul>
  <li><a href="{% url 'home' %}">Home Page</a></li>
  <li><a href="{% url 'films:main' %}">Films Main Page</a></li>
  <li><a href="{% url 'films:user_info' %}">Films User_Info Page</a></li>
  <li><a href="http://localhost:8000/gapminder/2007">gapminder graph</a></li>
</ul>
{% endblock %}